### PR TITLE
Add isInitialized

### PR DESCRIPTION
**Pull request by nikibreg**

### CODE REVIEW

**Comment by dopry** [comment]
@nikibreg this looks like a good potential feature.  Could you share a little about your use case and what problems the isInitialized store is solving for you? Can you update the docs and showcase with the new store?

**Comment by nikibreg** [comment]
The use case was whenever I navigated on the login component, it didn't trigger a redirect to the authorization URL. 

I don't know if this is the best solution for it, but since UserManager is vital for everything else, I think it's necessary to have a way of ensuring it's initialized.

**Comment by dopry** [comment]
Why not wait until !$isLoading?

**Comment by nikibreg** [comment]
Tried it, but it doesn't fire when UserManager stays falsy

**Comment by dopry** [comment]
Oh that's interesting. You don't by chance know how to reproduce making
UserManager falsy? I see your point. Update the docs and give me a scenario
I can test and I'd be good with merging this

**Comment by dopry** [comment]
If you get a chance to provide a scenario to go with this, please re-open.

**Pull request closed without merging**
